// Auto-generated base summaries for RoycoDayAccountant
// Generated by setup_summaries.py

import "EIP712.spec";
import "FixedPointMathLib.spec";
import "OpenZeppelin/OZ_Math-RoycoDayAccountant.spec";
import "OpenZeppelin/OZ_SafeERC20.spec";
import "OpenZeppelin/OZ_ShortStrings.spec";
import "OpenZeppelin/OZ_Strings.spec";
